// Todos os comandos "/" — organizados por categoria.

export type SlashCat = { id: string; label: string; emoji: string };
export type Slash = { cmd: string; oQueFaz: string; saida: string; cat: string };

export const SLASH_CATS: SlashCat[] = [
  { id: "basicos",   label: "Básicos",    emoji: "⭐" },
  { id: "pesquisa",  label: "Pesquisa",   emoji: "🔍" },
  { id: "criar",     label: "Criar",      emoji: "⚡" },
  { id: "github",    label: "GitHub",     emoji: "🐙" },
  { id: "automacao", label: "Automação",  emoji: "🤖" },
  { id: "gsd",       label: "GSD",        emoji: "💪" },
  { id: "seo",       label: "SEO",        emoji: "📈" },
  { id: "ruflo",     label: "RUFLO",      emoji: "🐝" },
  { id: "contexto",  label: "Contexto",   emoji: "🧠" },
];

export const SLASHES: Slash[] = [
  // ── BÁSICOS ──────────────────────────────────────────────────────
  { cat: "basicos", cmd: "/help",
    oQueFaz: "Lista TUDO que existe na sua sessão. Perdeu? Começa sempre aqui — é a fonte da verdade.",
    saida: "Listando comandos disponíveis… /help /clear /compact /model /effort /plan /deep-research /schedule e muito mais." },
  { cat: "basicos", cmd: "/clear",
    oQueFaz: "Limpa a conversa e zera a memória. Use quando a conversa embolou os assuntos.",
    saida: "Conversa limpa. Memória zerada. Pode recomeçar, capitão." },
  { cat: "basicos", cmd: "/compact",
    oQueFaz: "Resume uma conversa longa sem perder o fio. Libera espaço e mantém o contexto.",
    saida: "Histórico comprimido num resumo inteligente. Espaço liberado, contexto preservado." },
  { cat: "basicos", cmd: "/model",
    oQueFaz: "Troca o 'cérebro' da IA — rápido e leve ou devagar e profundo.",
    saida: "Modelos disponíveis: Haiku (rápido) · Sonnet (equilibrado) · Opus (máximo raciocínio)." },
  { cat: "basicos", cmd: "/effort",
    oQueFaz: "Define quanto esforço a IA coloca: do modo rápido ao máximo.",
    saida: "Esforço definido. Pergunta simples = rápido; decisão de negócio = máximo." },
  { cat: "basicos", cmd: "/plan",
    oQueFaz: "Ela te mostra o PLANO antes de executar. Você confere e aprova, depois ela age.",
    saida: "Aqui está meu plano antes de tocar em qualquer coisa: 1)… 2)… 3)… Aprova, capitão?" },
  { cat: "basicos", cmd: "/fast",
    oQueFaz: "Ativa o modo turbo — respostas mais rápidas com o Opus. Toggle on/off.",
    saida: "Modo rápido ativado. Respondendo em alta velocidade com Opus." },
  { cat: "basicos", cmd: "/init",
    oQueFaz: "Inicializa a IA no contexto do seu projeto — ela lê os arquivos e aprende o que existe.",
    saida: "Lendo o projeto… Encontrei 34 arquivos. Entendi a estrutura. Pode começar." },

  // ── PESQUISA ─────────────────────────────────────────────────────
  { cat: "pesquisa", cmd: "/deep-research",
    oQueFaz: "Pesquisa pesada com fontes reais — para decisão grande, não pergunta rápida.",
    saida: "Soltando a tripulação: lendo dezenas de fontes, montando relatório com citações…" },
  { cat: "pesquisa", cmd: "/review",
    oQueFaz: "Revisão detalhada de qualquer coisa — texto, código, plano, ideia.",
    saida: "Analisando com lupa: qualidade, clareza, pontos cegos, inconsistências…" },
  { cat: "pesquisa", cmd: "/code-review",
    oQueFaz: "Revisa código e encontra bugs, brechas de segurança e melhorias.",
    saida: "Passando o pente fino: bugs, segurança, eficiência, duplicação… Relatório em 2 min." },
  { cat: "pesquisa", cmd: "/security-review",
    oQueFaz: "Auditoria de segurança — encontra vulnerabilidades antes que alguém explore.",
    saida: "Checando portas abertas, senhas fracas, brechas de SQL, XSS… Relatório de segurança pronto." },
  { cat: "pesquisa", cmd: "/simplify",
    oQueFaz: "Simplifica código complicado sem mudar o que ele faz — deixa mais limpo.",
    saida: "Limpando, reorganizando, removendo duplicação… Código 40% mais simples entregue." },

  // ── CRIAR & EXECUTAR ──────────────────────────────────────────────
  { cat: "criar", cmd: "/sparc:code",
    oQueFaz: "Escreve qualquer código do zero com metodologia estruturada (Spec + Plan + Code).",
    saida: "Especificando + planejando + codificando + testando… Solução completa entregue." },
  { cat: "criar", cmd: "/sparc:debug",
    oQueFaz: "Encontra e corrige problemas difíceis com método científico — hipóteses e testes.",
    saida: "Hipótese 1: falha na validação de input. Testando… Confirmado! Correção aplicada." },
  { cat: "criar", cmd: "/sparc:architect",
    oQueFaz: "Projeta a arquitetura de um sistema complexo antes de construir qualquer coisa.",
    saida: "Analisando requisitos… Diagrama de arquitetura e decisões documentadas." },
  { cat: "criar", cmd: "/sparc:tdd",
    oQueFaz: "Escreve testes ANTES do código — garante que tudo funciona de verdade.",
    saida: "Testes escritos primeiro. Código que falha > refatorando > verde. TDD completo." },
  { cat: "criar", cmd: "/sparc:researcher",
    oQueFaz: "Pesquisa em profundidade um tema técnico e entrega um relatório estruturado.",
    saida: "Varrendo documentação, artigos, benchmarks… Relatório de pesquisa técnica pronto." },
  { cat: "criar", cmd: "/run",
    oQueFaz: "Roda o projeto e te mostra o que está acontecendo na tela.",
    saida: "Iniciando o servidor… Projeto rodando em localhost:3000. Sem erros." },
  { cat: "criar", cmd: "/verify",
    oQueFaz: "Verifica se as mudanças que foram feitas realmente funcionam na prática.",
    saida: "Testando no browser… Feature confirmada. Sem regressões. Tudo funcionando." },

  // ── GITHUB ────────────────────────────────────────────────────────
  { cat: "github", cmd: "/github:code-review",
    oQueFaz: "Revisa Pull Requests do GitHub com olhar técnico — encontra o que humano perderia.",
    saida: "Analisando diff de 847 linhas… 3 bugs encontrados, 7 melhorias sugeridas. Comentários adicionados." },
  { cat: "github", cmd: "/github:pr-manager",
    oQueFaz: "Gerencia todo o ciclo de vida de Pull Requests — abre, revisa, aprova, faz merge.",
    saida: "PR aberto, revisores notificados, checks passando, aprovações coletadas… Pronto pro merge." },
  { cat: "github", cmd: "/github:release-manager",
    oQueFaz: "Orquestra lançamentos de versão do início ao fim — changelog, tags, deploy.",
    saida: "Changelog gerado, versão taggeada, release publicada no GitHub… v2.0 no ar!" },
  { cat: "github", cmd: "/github:issue-tracker",
    oQueFaz: "Rastreia e organiza issues do projeto automaticamente.",
    saida: "32 issues categorizadas por prioridade, assignadas aos responsáveis. Backlog organizado." },
  { cat: "github", cmd: "/github:repo-analyze",
    oQueFaz: "Analisa repositório inteiro — saúde, padrões, dívida técnica, pontos de risco.",
    saida: "Varrendo todos os arquivos… Saúde: 78/100. Top risco: auth sem testes. Relatório pronto." },
  { cat: "github", cmd: "/github:workflow-automation",
    oQueFaz: "Cria pipelines de CI/CD no GitHub Actions que rodam testes e deploy automaticamente.",
    saida: "Pipeline criada: push > testes > build > deploy em staging > aprovação > produção." },

  // ── AUTOMAÇÃO ─────────────────────────────────────────────────────
  { cat: "automacao", cmd: "/schedule",
    oQueFaz: "Agenda uma tarefa pra rodar sozinha num horário — ex: briefing toda manhã.",
    saida: "Tarefa agendada: toda segunda às 8h. Roda sozinha, sem você precisar pedir." },
  { cat: "automacao", cmd: "/loop",
    oQueFaz: "Repete um comando em intervalos automáticos — fica monitorando por você.",
    saida: "Loop ativo. Checando a cada 5 minutos. Notificando quando algo importante mudar." },
  { cat: "automacao", cmd: "/automation:workflow-select",
    oQueFaz: "Analisa sua tarefa e escolhe o fluxo de trabalho ideal para executá-la.",
    saida: "Analisando complexidade… Workflow recomendado: pipeline paralelo com verificação." },
  { cat: "automacao", cmd: "/automation:self-healing",
    oQueFaz: "IA que detecta seus próprios erros e tenta se corrigir automaticamente.",
    saida: "Erro detectado na linha 47. Tentativa de autocorreção 1… Resolvido. Continuando." },
  { cat: "automacao", cmd: "/automation:session-memory",
    oQueFaz: "Salva o contexto da sessão pra continuar de onde parou em outra conversa.",
    saida: "Sessão salva: 3 tarefas em progresso, contexto preservado. Pode fechar e voltar." },

  // ── GSD (GET SHIT DONE) ───────────────────────────────────────────
  { cat: "gsd", cmd: "/gsd-do",
    oQueFaz: "Executa tarefas direto, sem burocracia — máxima velocidade, mínima pergunta.",
    saida: "Modo turbo ativado. Executando agora. Zero perguntas desnecessárias." },
  { cat: "gsd", cmd: "/gsd-debug",
    oQueFaz: "Debugga problemas complexos com método científico (hipótese + teste + conclusão).",
    saida: "Hipótese 1: estado corrompido. Hipótese 2: race condition. Testando… H2 confirmada." },
  { cat: "gsd", cmd: "/gsd-progress",
    oQueFaz: "Mostra o progresso de todas as tarefas em andamento — o que está feito e o que falta.",
    saida: "Fase 1 (100%) · Fase 2 (67%) · Fase 3 (aguardando). ETA: 23 min." },
  { cat: "gsd", cmd: "/gsd-next",
    oQueFaz: "Descobre qual é a próxima tarefa mais importante e começa ela imediatamente.",
    saida: "Próxima prioridade: implementar autenticação (bloqueador de 3 outras tarefas). Começando." },
  { cat: "gsd", cmd: "/gsd-plan-phase",
    oQueFaz: "Planeja uma fase do projeto com pesquisa, análise de padrões e plano de execução.",
    saida: "Pesquisando contexto… Padrões encontrados… Plano detalhado com 12 tarefas montado." },
  { cat: "gsd", cmd: "/gsd-new-project",
    oQueFaz: "Cria um projeto novo do zero — roadmap completo, fases, tarefas, critérios de sucesso.",
    saida: "Pesquisando domínio… Roadmap criado: 8 fases, 47 tarefas. Pronto pra zarpar!" },
  { cat: "gsd", cmd: "/gsd-review",
    oQueFaz: "Revisão completa de uma fase — o que foi feito, o que falta, qualidade do resultado.",
    saida: "Verificando implementação vs plano… 11/12 tarefas completas. 1 pendente: testes de integração." },
  { cat: "gsd", cmd: "/gsd-health",
    oQueFaz: "Checagem geral da saúde do projeto — código, testes, dependências, segurança.",
    saida: "Saúde geral: 83/100. Pontos de atenção: cobertura de testes (58%) e 2 deps desatualizadas." },

  // ── SEO ───────────────────────────────────────────────────────────
  { cat: "seo", cmd: "/seo",
    oQueFaz: "Auditoria SEO completa do site — tudo que o Google quer que você arrume, num relatório.",
    saida: "Auditando crawlability, velocidade, conteúdo, schema, backlinks… Relatório SEO completo pronto." },
  { cat: "seo", cmd: "/seo:technical",
    oQueFaz: "SEO técnico profundo — rastreabilidade, indexação, mobile, segurança, JavaScript rendering.",
    saida: "Checando robots.txt, sitemap, status 404, canonical, hreflang… Relatório técnico pronto." },
  { cat: "seo", cmd: "/seo:performance",
    oQueFaz: "Core Web Vitals e velocidade de carregamento — o Google mede isso pra rankear você.",
    saida: "LCP: 2.1s · FID: 18ms · CLS: 0.02 — Bom! 3 otimizações recomendadas para mobile." },
  { cat: "seo", cmd: "/seo:content",
    oQueFaz: "Qualidade do conteúdo — sinal de autoridade, E-E-A-T, profundidade, palavras finas.",
    saida: "Conteúdo avaliado: autoridade ALTA · profundidade MÉDIA · 3 páginas com conteúdo raso detectadas." },
  { cat: "seo", cmd: "/seo:schema",
    oQueFaz: "Schema markup — dados estruturados que ajudam o Google a entender e destacar seu site.",
    saida: "Schema Organization, LocalBusiness e WebSite detectados. FAQ Schema ausente — recomendo adicionar." },
  { cat: "seo", cmd: "/seo:local",
    oQueFaz: "SEO local — Google Maps, Google Business, consistência NAP, avaliações.",
    saida: "GBP: completo · NAP consistente em 12 diretórios · 4.7 estrelas · Recomendação: mais fotos de serviço." },
  { cat: "seo", cmd: "/seo:geo",
    oQueFaz: "GEO — otimização pra IA Overviews, Perplexity, ChatGPT e outros buscadores de IA.",
    saida: "Rastreamento por IA: Googlebot-Extended: permitido · llms.txt: ausente · citabilidade: BAIXA. Ações recomendadas." },
  { cat: "seo", cmd: "/seo:sitemap",
    oQueFaz: "Cria e valida o sitemap XML — o mapa que o Google usa pra descobrir suas páginas.",
    saida: "Sitemap validado: 47 URLs · 2 páginas 404 removidas · sitemap submetido ao Google Search Console." },

  // ── RUFLO / SWARM ─────────────────────────────────────────────────
  { cat: "ruflo", cmd: "/swarm",
    oQueFaz: "Lança uma frota de IAs trabalhando em paralelo pra completar tarefas complexas.",
    saida: "Swarm iniciado: 8 agentes ativos. Agente 1: pesquisa · Agente 2: redação · Agente 3: revisão…" },
  { cat: "ruflo", cmd: "/swarm-init",
    oQueFaz: "Inicializa e configura o swarm antes de começar — define topologia e número de agentes.",
    saida: "Swarm configurado: topologia mesh · 6 agentes especializados · memória compartilhada ativa." },
  { cat: "ruflo", cmd: "/hive-mind:spawn",
    oQueFaz: "Cria uma mente coletiva de IAs que tomam decisões por consenso — pra problemas difíceis.",
    saida: "Hive Mind ativo: 5 IAs votando em consenso. Bias individual eliminado. Decisão coletiva em progresso…" },
  { cat: "ruflo", cmd: "/hive-mind:status",
    oQueFaz: "Mostra o que a mente coletiva está fazendo agora — agentes, tarefas, consenso atual.",
    saida: "Hive Mind: 5 agentes ativos · consenso em 3 tarefas · 1 divergência registrada · saúde: 97%" },
  { cat: "ruflo", cmd: "/memory:store",
    oQueFaz: "Salva qualquer informação na memória persistente — disponível em qualquer conversa futura.",
    saida: "Memória salva com sucesso. Disponível em todas as sessões futuras com tag #negocio-charter." },
  { cat: "ruflo", cmd: "/memory:search",
    oQueFaz: "Busca na memória persistente — encontra o que você já ensinou pra IA em sessões anteriores.",
    saida: "Buscando… Encontrei 8 memorias relevantes sobre charter de barcos. Carregando contexto…" },
  { cat: "ruflo", cmd: "/autopilot:enable",
    oQueFaz: "Ativa o autopiloto — a IA completa tarefas multi-etapa sozinha sem você precisar aprovar cada passo.",
    saida: "Autopiloto ativado. Executando sequência de 12 tarefas de forma autônoma. Notificando só se encontrar bloqueio." },
  { cat: "ruflo", cmd: "/agent:spawn",
    oQueFaz: "Cria um agente especializado pra uma tarefa específica — SEO, redação, análise, código.",
    saida: "Agente especialista criado: tipo=redacao-charter · contexto=AYC carregado · pronto para receber tarefas." },

  // ── CONTEXTO ─────────────────────────────────────────────────────
  { cat: "contexto", cmd: "/context",
    oQueFaz: "Monta o contexto completo antes de qualquer tarefa — quem você é, o que quer, o que existe. Contexto bom = resultado bom.",
    saida: "Contexto montado: negócio (charter de barcos) · objetivo (email de confirmação) · tom (caloroso) · restrições (sem inventar preço). Pronto pra tarefa." },
  { cat: "contexto", cmd: "/context:negocio",
    oQueFaz: "Carrega o contexto completo do seu negócio — o que você faz, quem são seus clientes, como você opera.",
    saida: "Contexto do negócio carregado: Atlantic Yacht Charter · 3 embarcações · clientes VIP · base em Fortaleza." },
  { cat: "contexto", cmd: "/context:projeto",
    oQueFaz: "Carrega o contexto de um projeto específico — histórico, decisões, participantes, próximos passos.",
    saida: "Contexto do projeto carregado: 14 decisões registradas · 3 participantes · próximo passo: campanha de verão." },
  { cat: "contexto", cmd: "/context:decisao",
    oQueFaz: "Prepara a IA pra ajudar numa decisão — coleta contexto PURO antes de qualquer estratégia.",
    saida: "Modo decisão: coletando contexto. Vou fazer perguntas SÓ sobre fatos, nunca sobre opiniões ou preferências." },
];

// Passos de instalação — como chegar no Claude Code e instalar comandos.
export type InstalacaoPasso = { num: number; titulo: string; detalhe: string; codigo?: string };

export const INSTALACAO_PASSOS: InstalacaoPasso[] = [
  {
    num: 1,
    titulo: "Instale o Node.js (uma vez só)",
    detalhe: "O Node.js é o motor que roda o Claude Code no seu computador. Vai em nodejs.org e baixa a versão LTS.",
    codigo: "# Após instalar, confirme no terminal:\nnode --version",
  },
  {
    num: 2,
    titulo: "Instale o Claude Code (CLI)",
    detalhe: "Abra o Terminal (Aplicativos > Utilitários > Terminal no Mac). Cole o comando abaixo e aperte Enter.",
    codigo: "npm install -g @anthropic-ai/claude-code",
  },
  {
    num: 3,
    titulo: "Entre com sua conta Claude",
    detalhe: "Na primeira vez que rodar, ele vai pedir pra você fazer login com sua conta Claude.",
    codigo: "claude\n# Siga as instruções de login na tela",
  },
  {
    num: 4,
    titulo: "Instale os comandos do RUFLO (pacotão completo)",
    detalhe: "Este comando instala TODOS os atalhos do RUFLO — swarm, memória, autopiloto, tudo de uma vez.",
    codigo: "npx ruflo init",
  },
  {
    num: 5,
    titulo: "Crie um comando próprio seu",
    detalhe: "Qualquer arquivo .md na pasta ~/.claude/commands/ vira um slash command. Crie o seu assim:",
    codigo: "mkdir -p ~/.claude/commands\nnano ~/.claude/commands/charter.md\n# Escreva as instruções do seu atalho\n# Salve com Ctrl+X, Y, Enter",
  },
];
